In [ ]:
# NUMPY ASSIGNMENT

In [1]:
# 1.Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np
arr = np.arange(6)
print(arr.dtype)


int64


In [2]:
# 2.Given a NumPy array 'arr', check if its data type is float64. 
#   arr = np.array([1.5, 2.6, 3.7])

import numpy as np
arr = np.array([1.5, 2.6, 3.7])
is_float64 = arr.dtype == np.float64
print(is_float64)


True


In [3]:
# 3.Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

import numpy as np
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)
print(arr.dtype)

[1.+2.j 3.+4.j 5.+6.j]
complex128


In [4]:
# 4.Convert an existing NumPy array 'arr' of integers to float32 data type.

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)
print(arr_float32)
print(arr_float32.dtype)

[1. 2. 3. 4. 5.]
float32


In [5]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

import numpy as np
arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)
print(arr_float32.dtype)
 

[1.1 2.2 3.3]
float32


In [6]:
# 6.Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

import numpy as np
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype
arr = np.array([1.1, 2.2, 3.3])
attributes = array_attributes(arr)
print(attributes)

((3,), 3, dtype('float64'))


In [7]:
# 7.Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

import numpy as np
def array_dimension(arr):
    return arr.ndim
arr = np.array([[1, 2, 3], [4, 5, 6]])
dimensionality = array_dimension(arr)
print(dimensionality)

2


In [8]:
# 8.Design a function item_size_info that takes a NumPy array as input and returns the item size and the 
#   total size in bytes.

import numpy as np
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size
arr = np.array([1.1, 2.2, 3.3])
size_info = item_size_info(arr)
print(size_info)

(8, 24)


In [9]:
# 9.Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

import numpy as np
def array_strides(arr):
    return arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)
print(strides)

(24, 8)


In [10]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape 
#     and strides of the array

import numpy as np
def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    return shape, strides
arr = np.array([[1, 2, 3], [4, 5, 6]])
relationship = shape_stride_relationship(arr)
print(relationship)

((2, 3), (24, 8))


In [11]:
# 11.Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of 
#    zeros with `n` elements.

import numpy as np
def create_zeros_array(n):
    return np.zeros(n)
n = 5
zeros_array = create_zeros_array(n)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [12]:
# 12.Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
#    NumPy array filled with ones of size `rows x cols`.

import numpy as np
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# 13.Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
#    creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 
#    `step`.

import numpy as np
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
array = generate_range_array(0, 10, 2)
print(array)

[0 2 4 6 8]


In [14]:
# 14.Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
#    arguments and generates a NumPy array with num equally spaced values between `start` and `stop` 
#    (inclusive).

import numpy as np
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)
array = generate_linear_space(0.0, 1.0, 5)
print(array)

[0.   0.25 0.5  0.75 1.  ]


In [15]:
# 15.Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
#    identity matrix of size `n x n` using `numpy.eye`.

import numpy as np
def create_identity_matrix(n):
    return np.eye(n)
identity_matrix = create_identity_matrix(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# 16.Write a function that takes a Python list and converts it into a NumPy array.

import numpy as np
def list_to_numpy_array(py_list):
    return np.array(py_list)
python_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(python_list)
print(numpy_array)

[1 2 3 4 5]


In [17]:
# 17.Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the 
#    same data.

import numpy as np
original_array = np.array([1, 2, 3, 4, 5])
view_array = original_array.view()
original_array[0] = 10
print("Original array:", original_array)
print("View array:", view_array)

Original array: [10  2  3  4  5]
View array: [10  2  3  4  5]


In [18]:
# 18.Write a function that takes two NumPy arrays and concatenates them along a specified axis.

import numpy as np
def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated_array_0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", concatenated_array_0)
concatenated_array_1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:\n", concatenated_array_1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [19]:
# 19.Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
#    concatenate`.

import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8], [9, 10]])
concatenated_array = np.concatenate((array1, array2), axis=1)
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Concatenated array:\n", concatenated_array)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8]
 [ 9 10]]
Concatenated array:
 [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [20]:
# 20.Write a function that vertically stacks multiple NumPy arrays given as a list.

import numpy as np
def vertical_stack_arrays(array_list):
    return np.vstack(array_list)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
array3 = np.array([[9, 10], [11, 12]])
arrays_to_stack = [array1, array2, array3]
stacked_array = vertical_stack_arrays(arrays_to_stack)
print(stacked_array)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [21]:
# 21.Write a Python function using NumPy to create an array of integers within a specified range (inclusive) 
#    with a given step size.

import numpy as np
def create_range_array(start, stop, step):
    return np.arange(start, stop + step, step)
array = create_range_array(1, 10, 2)
print(array)

[ 1  3  5  7  9 11]


In [22]:
# 22.Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 
#    (inclusive).

import numpy as np
def generate_equally_spaced_values():
    return np.linspace(0, 1, 10)
array = generate_equally_spaced_values()
print(array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
# 23.Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 
#    1000 (inclusive).

import numpy as np
def create_log_space_array():
    log_space_array = np.logspace(0, 3, num=5)
    return log_space_array
log_array = create_log_space_array()
print(log_array)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [24]:
# 24.Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values 
#    are random integers between 1 and 100.

import numpy as np
import pandas as pd
def create_random_dataframe():
    random_array = np.random.randint(1, 101, size=(5, 3))
    df = pd.DataFrame(random_array, columns=['Column1', 'Column2', 'Column3'])
    return df
random_df = create_random_dataframe()
print(random_df)

   Column1  Column2  Column3
0       19       82       19
1       79       17       67
2       86       30       33
3       49       64       79
4       46       19       59


In [25]:
# 25.Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
#    with zeros. Use NumPy operations within the Pandas DataFrame.

import numpy as np
import pandas as pd
def replace_negatives_with_zeros(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df
data = {
    'A': [1, -2, 3, -4, 5],
    'B': [-1, 2, -3, 4, -5],
    'C': [1, 2, 3, 4, 5]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
df = replace_negatives_with_zeros(df, 'A')
print("\nDataFrame after replacing negatives in column 'A':")
print(df)

Original DataFrame:
   A  B  C
0  1 -1  1
1 -2  2  2
2  3 -3  3
3 -4  4  4
4  5 -5  5

DataFrame after replacing negatives in column 'A':
   A  B  C
0  1 -1  1
1  0  2  2
2  3 -3  3
3  0  4  4
4  5 -5  5


In [26]:
# 26.Access the 3rd element from the given NumPy array.
#    arr = np.array([10, 20, 30, 40, 50])

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print(third_element)

30


In [27]:
# 27.Retrieve the element at index (1, 2) from the 2D NumPy array.
#    arr_2d = np.array([[1, 2, 3],

#    [4, 5, 6],

#    [7, 8, 9]])

import numpy as np
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
element = arr_2d[1, 2]
print(element)


6


In [28]:
# 28.Using boolean indexing, extract elements greater than 5 from the given NumPy array.
#    arr = np.array([3, 8, 2, 10, 5, 7])

import numpy as np
arr = np.array([3, 8, 2, 10, 5, 7])
mask = arr > 5
result = arr[mask]
print(result)

[ 8 10  7]


In [29]:
# 29.Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
#    arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_arr = arr[2:6]
print(sliced_arr)

[3 4 5 6]


In [30]:
# 30.Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
#    arr_2d = np.array([[1, 2, 3],

#                       [4, 5, 6],

#                       [7, 8, 9]])

import numpy as np
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]
print(sub_array)

[[2 3]
 [5 6]]


In [31]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices 
#    provided in another array.

import numpy as np
def extract_elements(arr, indices):
    return np.take(arr, indices)
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
indices = np.array([0, 4, 8])
extracted_elements = extract_elements(arr_2d, indices)
print(extracted_elements)

[1 5 9]


In [32]:
# 32.Create a NumPy function that filters elements greater than a threshold from a given 1D array using 
#    boolean indexing.

import numpy as np
def filter_greater_than(arr, threshold):
    return arr[arr > threshold]
arr = np.array([3, 8, 2, 10, 5, 7])
threshold = 5
filtered_arr = filter_greater_than(arr, threshold)
print(filtered_arr)

[ 8 10  7]


In [33]:
# 33.Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three 
#    separate arrays for each dimension.

import numpy as np
def extract_elements_3d(arr, depth_indices, row_indices, col_indices):
    return arr[depth_indices, row_indices, col_indices]
arr_3d = np.array([[[ 1,  2,  3],
                    [ 4,  5,  6],
                    [ 7,  8,  9]],
                   
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])
depth_indices = np.array([0, 1, 2])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
extracted_elements = extract_elements_3d(arr_3d, depth_indices, row_indices, col_indices)
print(extracted_elements)

[ 2 15 25]


In [34]:
# 34.Write a NumPy function that returns elements from an array where both two conditions are satisfied 
#    using boolean indexing.

import numpy as np
def filter_array(arr, condition1, condition2):
    return arr[(condition1) & (condition2)]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition1 = arr > 3
condition2 = arr < 8
filtered_arr = filter_array(arr, condition1, condition2)
print(filtered_arr)


[4 5 6 7]


In [35]:
# 35.Create a NumPy function that extracts elements from a 2D array using row and column indices provided 
#    in separate arrays.

import numpy as np
def extract_elements(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 0, 1])
extracted_elements = extract_elements(arr, row_indices, col_indices)
print(extracted_elements)

[30 40 80]


In [1]:
# 36.Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = arr + 5
print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [2]:
# 37.Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
#    corresponding element in arr1 using NumPy broadcasting.

import numpy as np
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
result = arr2 * arr1.T
print(result)

[[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


In [4]:
# 38.Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

import numpy as np
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13], [14, 15, 16]])
result = arr2 + arr1.T
print(result)

[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [7]:
# 39.Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy 
#    broadcasting.

import numpy as np
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
result = arr1 + arr2
print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [8]:
# 40.Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy 
#    broadcasting. Handle the shape incompatibility.

import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])
arr2_expanded = arr2[:, :, np.newaxis]
result = arr1 * arr2_expanded
print(result)

[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


In [9]:
# 41.Calculate column-wise mean for the given array:
#    arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean = np.mean(arr, axis=0)
print(column_mean)

[2.5 3.5 4.5]


In [10]:
# 42.Find maximum value in each row of the given array:
#    arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = np.max(arr, axis=1)
print(row_max)

[3 6]


In [11]:
# 43.For the given array, find indices of maximum value in each column.
#    arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_max_indices = np.argmax(arr, axis=0)
print(column_max_indices)

[1 1 1]


In [12]:
# 44.For the given array, apply custom function to calculate moving sum along rows.
#    arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
def moving_sum(arr, window_size):
    result = np.zeros_like(arr)
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            start = max(0, j - window_size + 1)
            result[i, j] = np.sum(arr[i, start:j+1])
    return result
window_size = 2
moving_sum_result = moving_sum(arr, window_size)
print(moving_sum_result)

[[ 1  3  5]
 [ 4  9 11]]


In [13]:
# 45.In the given array, check if all elements in each column are even.
#    arr = np.array([[2, 4, 6], [3, 5, 7]])

import numpy as np
arr = np.array([[2, 4, 6], [3, 5, 7]])
all_even_columns = np.all(arr % 2 == 0, axis=0)
print(all_even_columns)

[False False False]


In [16]:
# 46.Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the 
#    reshaped matrix.
#    original_array = np.array([1, 2, 3, 4, 5, 6])

import numpy as np
original_array = np.array([1, 2, 3, 4, 5, 6])
m, n = 2, 3
reshaped_matrix = original_array.reshape(m, n)
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


In [17]:
# 47.Create a function that takes a matrix as input and returns the flattened array.
#    input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np
def flatten_matrix(matrix):
    return matrix.flatten()
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


In [19]:
# 48. Write a function that concatenates two given arrays along a specified axis.
#     array1 = np.array([[1, 2], [3, 4]])

#     array2 = np.array([[5, 6], [7, 8]])

import numpy as np
def concatenate_arrays(array1, array2, axis):
    return np.concatenate((array1, array2), axis=axis)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated_array = concatenate_arrays(array1, array2, axis=0)
print(concatenated_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [21]:
# 49.Create a function that splits an array into multiple sub-arrays along a specified axis.
#    original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

import numpy as np
def split_array(array, indices_or_sections, axis):
    return np.split(array, indices_or_sections, axis=axis)
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_arrays = split_array(original_array, 3, axis=0)
print(sub_arrays)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [22]:
# 50.Write a function that inserts and then deletes elements from a given array at specified indices.
#    original_array = np.array([1, 2, 3, 4, 5])

#    indices_to_insert = [2, 4]

#    values_to_insert = [10, 11]

#    indices_to_delete = [1, 3]

import numpy as np
def insert_and_delete_elements(array, insert_indices, insert_values, delete_indices):
    array = np.insert(array, insert_indices, insert_values)
    array = np.delete(array, delete_indices)
    return array
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result_array)

[ 1 10  4 11  5]


In [23]:
# 51.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
#    Perform element-wise addition between `arr1` and `arr2`.

import numpy as np
arr1 = np.random.randint(1, 11, size=10)  # Random integers between 1 and 10, array of size 10
arr2 = np.arange(1, 11)
result = arr1 + arr2
print("arr1:", arr1)
print("arr2:", arr2)
print("Result:", result)

arr1: [2 4 2 1 3 3 2 5 4 9]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result: [ 3  6  5  5  8  9  9 13 13 19]


In [24]:
# 52.Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers 
#    from 1 to 10. Subtract `arr2` from `arr1` element-wise.

import numpy as np
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2
print("arr1:", arr1)
print("arr2:", arr2)
print("Result:", result)

arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [25]:
# 53.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
#    Perform element-wise multiplication between `arr1` and `arr2`.

import numpy as np
arr1 = np.random.randint(1, 10, size=5)
arr2 = np.arange(1, 6)
result = np.multiply(arr1, arr2)
print("arr1:", arr1)
print("arr2:", arr2)
print("Result:", result)

arr1: [3 3 8 7 4]
arr2: [1 2 3 4 5]
Result: [ 3  6 24 28 20]


In [26]:
# 54.Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 
#    to 5. Perform element-wise division of `arr1` by `arr2`.

import numpy as np
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
result = np.divide(arr1, arr2)
print("arr1:", arr1)
print("arr2:", arr2)
print("Result:", result)

arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Result: [2. 2. 2. 2. 2.]


In [27]:
# 55.Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
#    reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise

import numpy as np
arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
result = np.power(arr1, arr2)
print("arr1:", arr1)
print("arr2:", arr2)
print("Result:", result)

arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Result: [ 1 16 27 16  5]


In [28]:
# 56.Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
#    arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

import numpy as np
def count_substring(arr, substring):
    return np.char.count(arr, substring)
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
result = count_substring(arr, substring)
print("Array:", arr)
print(f"Occurrences of '{substring}':", result)

Array: ['hello' 'world' 'hello' 'numpy' 'hello']
Occurrences of 'hello': [1 0 1 0 1]


In [29]:
# 57.Write a function that extracts uppercase characters from a NumPy array of strings.
#    arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
#    arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

import numpy as np
def extract_uppercase(arr):
    uppercase_chars = np.char.join('', np.char.split(arr))
    return np.array([''.join([char for char in word if char.isupper()]) for word in uppercase_chars])
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
result = extract_uppercase(arr)
print("Array:", arr)
print("Uppercase characters:", result)

Array: ['Hello' 'World' 'OpenAI' 'GPT']
Uppercase characters: ['H' 'W' 'OAI' 'GPT']


In [30]:
# 58.Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
#    arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

import numpy as np
def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'
result = replace_substring(arr, old_substring, new_substring)
print("Array:", arr)
print(f"Array after replacing '{old_substring}' with '{new_substring}':", result)

Array: ['apple' 'banana' 'grape' 'pineapple']
Array after replacing 'apple' with 'orange': ['orange' 'banana' 'grape' 'pineorange']


In [31]:
# 59.Write a function that concatenates strings in a NumPy array element-wise.
#    arr1 = np.array(['Hello', 'World'])

#    arr2 = np.array(['Open', 'AI'])

import numpy as np
def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
result = concatenate_strings(arr1, arr2)
print("arr1:", arr1)
print("arr2:", arr2)
print("Concatenated result:", result)

arr1: ['Hello' 'World']
arr2: ['Open' 'AI']
Concatenated result: ['HelloOpen' 'WorldAI']


In [32]:
# 60.Write a function that finds the length of the longest string in a NumPy array.
#    arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
#    arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

import numpy as np
def length_of_longest_string(arr):
    longest_string = max(arr, key=len)
    return len(longest_string)
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = length_of_longest_string(arr)
print("Array:", arr)
print("Length of the longest string:", result)

Array: ['apple' 'banana' 'grape' 'pineapple']
Length of the longest string: 9


In [34]:
# 61.Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
#   standard deviation of the dataset using NumPy's functions.

import numpy as np
dataset = np.random.randint(1, 1001, size=100)
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)
print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)

Dataset: [152 541 830  92   1 193 522 366 980 492 391 461 380 283 913 716 181 812
 294 734 896 217  58 793 541 436 196 276 393 607  90 980  47  31 966 344
 926 694 921 553 584 747 853 497 837 738   5 391 945 849   8 306 738 521
 514 464 657 899 285 417 697  83 851 610 103 732 261 578 936 835 322  76
 314 834 222  87 617 291 659 396 455 905 424 848 339   5 384 901  42 616
 736 809 948 774 398 700 210 599  17 431]
Mean: 505.99
Median: 505.5
Variance: 86382.6099
Standard Deviation: 293.909186484533


In [35]:
# 62.Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the 
#   dataset.

import numpy as np
random_numbers = np.random.randint(1, 101, size=50)
percentile_25 = np.percentile(random_numbers, 25)
percentile_75 = np.percentile(random_numbers, 75)
print("Random Numbers:", random_numbers)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Random Numbers: [18 25 92 97 50 94 73  2 72 66 97 20 69 43 36 50 55 53 98 87 52 15  1 93
 33 31 42 33 89 94 12 84 49 79 38  5 28 46 23 91 20 16 54 78 98 55 74 63
 88  1]
25th Percentile: 28.75
75th Percentile: 82.75


In [36]:
# 63.Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
#    arrays using NumPy's `corrcoef` function.

import numpy as np
array1 = np.random.randint(1, 101, size=50)
array2 = np.random.randint(1, 101, size=50)
correlation_matrix = np.corrcoef(array1, array2)
correlation_coefficient = correlation_matrix[0, 1]
print("Array 1:", array1)
print("Array 2:", array2)
print("Correlation Coefficient Matrix:\n", correlation_matrix)
print("Correlation Coefficient:", correlation_coefficient)

Array 1: [31 74 51 67 67 61 18 45 96 94 58 40 51  4  5 52 97 51 27 25 45 67 72 44
 90 70 66 74 82 87 85 67 29 35 28 24 42 64 81 87 48 72  8 88 13 27 15 83
 83 89]
Array 2: [60 71 44 54  2 25 88  6 89 97 20 79 98 35 72 71 86 44 57 24 50 35 62 89
 64 19 33 67 14 98 46 52 69 55 10 88 75 14 71 84 60 99 81 93 76 44  8  5
 12 14]
Correlation Coefficient Matrix:
 [[1.        0.0331705]
 [0.0331705 1.       ]]
Correlation Coefficient: 0.03317050213618467


In [37]:
# 64.Create two matrices and perform matrix multiplication using NumPy's `dot` function.

import numpy as np
matrix1 = np.random.randint(1, 101, size=(3, 3))
matrix2 = np.random.randint(1, 101, size=(3, 3))
result = np.dot(matrix1, matrix2)
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Result of Matrix Multiplication:\n", result)

Matrix 1:
 [[70 10 10]
 [ 6 62  5]
 [13 24 61]]
Matrix 2:
 [[98 16 57]
 [87 98 16]
 [47 50 65]]
Result of Matrix Multiplication:
 [[8200 2600 4800]
 [6217 6422 1659]
 [6229 5610 5090]]


In [38]:
# 65.Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
#    percentiles along with the first and third quartiles.

import numpy as np
array = np.random.randint(10, 1001, size=50)
percentile_10 = np.percentile(array, 10)
percentile_50 = np.percentile(array, 50)
percentile_90 = np.percentile(array, 90)
first_quartile = np.percentile(array, 25)
third_quartile = np.percentile(array, 75)
print("Array:", array)
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", first_quartile)
print("Third Quartile (75th Percentile):", third_quartile)

Array: [595 806 320  13 227 191 914 130 896 299 305 549 515 954 920 678 800 763
 287 557 617 319 976 248 549 335 554 760 835 285 451 466 149  73  67 202
 186 149 728 845  66 309 810 943 567 300 207 458 406 135]
10th Percentile: 134.5
50th Percentile (Median): 454.5
90th Percentile: 897.8000000000001
First Quartile (25th Percentile): 232.25
Third Quartile (75th Percentile): 752.0


In [39]:
# 66.Create a NumPy array of integers and find the index of a specific element.

import numpy as np
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
element_to_find = 50
index = np.where(array == element_to_find)[0][0]
print("Array:", array)
print("Element to find:", element_to_find)
print("Index of the element:", index)

Array: [ 10  20  30  40  50  60  70  80  90 100]
Element to find: 50
Index of the element: 4


In [40]:
# 67.Generate a random NumPy array and sort it in ascending order.

import numpy as np
random_array = np.random.randint(1, 101, size=50)
sorted_array = np.sort(random_array)
print("Random Array:", random_array)
print("Sorted Array:", sorted_array)

Random Array: [ 61  99  48  16  53  29  13  92  48   6  81  48  40  59 100   5  94  50
   1  36  58  68  97  54  69   5   5  24  51  93  58  25  81  87  28  49
   8  18  48  58  78  66  93  14  76  79  49  35  25 100]
Sorted Array: [  1   5   5   5   6   8  13  14  16  18  24  25  25  28  29  35  36  40
  48  48  48  48  49  49  50  51  53  54  58  58  58  59  61  66  68  69
  76  78  79  81  81  87  92  93  93  94  97  99 100 100]


In [41]:
# 68.Filter elements >20  in the given NumPy array.
#    arr = np.array([12, 25, 6, 42, 8, 30])

import numpy as np
arr = np.array([12, 25, 6, 42, 8, 30])
filtered_arr = arr[arr > 20]
print("Original Array:", arr)
print("Filtered Array (elements > 20):", filtered_arr)

Original Array: [12 25  6 42  8 30]
Filtered Array (elements > 20): [25 42 30]


In [42]:
# 69.Filter elements which are divisible by 3 from a given NumPy array.
#    arr = np.array([1, 5, 8, 12, 15])

import numpy as np
arr = np.array([1, 5, 8, 12, 15])
filtered_arr = arr[arr % 3 == 0]
print("Original Array:", arr)
print("Filtered Array (elements divisible by 3):", filtered_arr)

Original Array: [ 1  5  8 12 15]
Filtered Array (elements divisible by 3): [12 15]


In [43]:
# 70.Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
#    arr = np.array([10, 20, 30, 40, 50])

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr >= 20) & (arr <= 40)]
print("Original Array:", arr)
print("Filtered Array (elements ≥ 20 and ≤ 40):", filtered_arr)

Original Array: [10 20 30 40 50]
Filtered Array (elements ≥ 20 and ≤ 40): [20 30 40]


In [44]:
# 71.For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
#    arr = np.array([1, 2, 3])

import numpy as np
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print("Array:", arr)
print("Byte Order:", byte_order)

Array: [1 2 3]
Byte Order: =


In [45]:
# 72.For the given NumPy array, perform byte swapping in place using `byteswap()`.
#    arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print("Array after byte swapping:", arr)

Array after byte swapping: [16777216 33554432 50331648]


In [46]:
# 73.For the given NumPy array, swap its byte order without modifying the original array using 
#    `newbyteorder()`.
#    arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.byteswap().newbyteorder()
print("Original array:", arr)
print("Swapped byte order array:", swapped_arr)

Original array: [1 2 3]
Swapped byte order array: [1 2 3]


In [47]:
# 74.For the given NumPy array and swap its byte order conditionally based on system endianness using 
#    `newbyteorder()`.
#    arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':  # Native byte order
    native_endian = np.dtype(np.int32).newbyteorder('=')
else:
    native_endian = arr.dtype
swapped_arr = arr.byteswap().newbyteorder() if native_endian.byteorder == '>' else arr
print("Original array:", arr)
print("Swapped byte order array:", swapped_arr)

Original array: [1 2 3]
Swapped byte order array: [1 2 3]


In [48]:
# 75.For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` 
#    attribute `byteorder`.
#    arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':  # Native byte order
    print("No byte swapping necessary.")
else:
    print("Byte swapping necessary.")
print("Array byte order:", arr.dtype.byteorder)

No byte swapping necessary.
Array byte order: =


In [49]:
# 76.Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
#    an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

import numpy as np
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 99
print("Original array (arr1):", arr1)
print("Copied and modified array (copy_arr):", copy_arr)

Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Copied and modified array (copy_arr): [99  2  3  4  5  6  7  8  9 10]


In [51]:
# 77.Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
#    the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

import numpy as np
matrix = np.random.randint(1, 100, size=(3, 3))
view_slice = matrix[1:, 1:]
view_slice[0, 0] = 999
print("Original matrix:\n", matrix)
print("View slice:\n", view_slice)

Original matrix:
 [[ 42  63  95]
 [ 35 999  36]
 [ 73  35  97]]
View slice:
 [[999  36]
 [ 35  97]]


In [52]:
# 78.Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
#    `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

import numpy as np
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[1:3, 1:3]
view_b += 5
print("Original array (array_a):\n", array_a)
print("View slice (view_b):\n", view_b)

Original array (array_a):
 [[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]
View slice (view_b):
 [[10 11]
 [13 14]]


In [53]:
# 79.Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
#    `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
#    reflects changes in the original `orig_array`.

import numpy as np
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 99
print("Original array (orig_array):\n", orig_array)
print("Reshaped view (reshaped_view):\n", reshaped_view)

Original array (orig_array):
 [[99  2  3  4]
 [ 5  6  7  8]]
Reshaped view (reshaped_view):
 [[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


In [54]:
# 80.Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
#    elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

import numpy as np
data = np.random.randint(1, 20, size=(3, 4))
data_copy = data[data > 5].copy()
if data_copy.size > 0:  # Ensure there are elements greater than 5
    data_copy[0] = 99
print("Original array (data):\n", data)
print("Copied array (data_copy):\n", data_copy)

Original array (data):
 [[ 9 16 11  6]
 [18  3  8 12]
 [ 2  3 12  3]]
Copied array (data_copy):
 [99 16 11  6 18  8 12 12]


In [55]:
# 81.Create two matrices A and B of identical shape containing integers and perform addition and subtraction 
#    operations between them.

import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
addition_result = A + B
subtraction_result = A - B
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition of A and B:\n", addition_result)
print("Subtraction of A and B:\n", subtraction_result)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition of A and B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction of A and B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [56]:
# 82.Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

import numpy as np
C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])
result = np.dot(C, D)
print("Matrix C:\n", C)
print("Matrix D:\n", D)
print("Matrix multiplication result (C * D):\n", result)

Matrix C:
 [[1 2]
 [3 4]
 [5 6]]
Matrix D:
 [[ 7  8  9 10]
 [11 12 13 14]]
Matrix multiplication result (C * D):
 [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [57]:
# 83.Create a matrix `E` and find its transpose.

import numpy as np
E = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
transpose_E = E.T
print("Matrix E:\n", E)
print("Transpose of matrix E:\n", transpose_E)

Matrix E:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of matrix E:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [58]:
# 84.Generate a square matrix `F` and compute its determinant.

import numpy as np
F = np.random.randint(1, 10, size=(3, 3))
determinant_F = np.linalg.det(F)
print("Matrix F:\n", F)
print("Determinant of matrix F:", determinant_F)

Matrix F:
 [[5 3 9]
 [8 9 9]
 [4 3 4]]
Determinant of matrix F: -50.99999999999997


In [59]:
# 85.Create a square matrix `G` and find its inverse.

import numpy as np
G = np.array([[4, 7], [2, 6]])
inverse_G = np.linalg.inv(G)
print("Matrix G:\n", G)
print("Inverse of matrix G:\n", inverse_G)

Matrix G:
 [[4 7]
 [2 6]]
Inverse of matrix G:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
